import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./content/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#181d10",
        "on-primary-fixed": "#410004",
        secondary: "#5b614f",
        "on-primary": "#ffffff",
        "on-surface-variant": "#584140",
        "on-secondary-container": "#5f6553",
        "on-surface-muted": "#5F5D58",
        "tertiary-fixed-dim": "#89d3d8",
        "on-tertiary-container": "#90d9df",
        "surface-bright": "#fff8f7",
        "accent-lavender": "#B4A7D6",
        "surface-container-highest": "#f4dddb",
        "primary-fixed-dim": "#ffb3ae",
        surface: "#F5F3EE",
        "surface-container-low": "#fff0ef",
        "inverse-on-surface": "#ffedeb",
        "inverse-primary": "#ffb3ae",
        outline: "#8b716f",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        tertiary: "#00474b",
        "accent-blue": "#8A9EB7",
        "secondary-fixed-dim": "#c3c9b3",
        "inverse-surface": "#3b2d2c",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#004f53",
        "on-background": "#241918",
        "surface-dim": "#ebd5d3",
        "surface-container-high": "#fae3e1",
        "secondary-fixed": "#dfe5cf",
        "primary-container": "#9f2d2d",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#434938",
        "surface-tint": "#a93534",
        "secondary-container": "#dce2cc",
        "primary-fixed": "#ffdad7",
        "on-surface": "#171717",
        "on-primary-container": "#ffbcb7",
        "on-tertiary-fixed": "#002022",
        "surface-variant": "#f4dddb",
        "error-container": "#ffdad6",
        border: "rgba(23, 23, 23, 0.18)",
        "on-secondary": "#ffffff",
        background: "#fff8f7",
        "accent-yellow": "#E8C581",
        "surface-container": "#ffe9e7",
        "tertiary-container": "#006166",
        "outline-variant": "#dfbfbd",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#891c1f",
        primary: "#7e1419",
        "tertiary-fixed": "#a5eff4",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "section-desktop": "96px",
        "section-mobile": "64px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        base: "4px",
        128: "128px",
      },
      fontFamily: {
        display: ["var(--font-garamond)", "EB Garamond", "serif"],
        "display-lg": ["var(--font-garamond)", "EB Garamond", "serif"],
        "display-lg-mobile": ["var(--font-garamond)", "EB Garamond", "serif"],
        "headline-md": ["var(--font-garamond)", "EB Garamond", "serif"],
        "headline-sm": ["var(--font-garamond)", "EB Garamond", "serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
